sudo: required
services:
  - docker

before_install:
  - docker build -e CI=true -t aliamyn/fibreact-test -f ./client/Dockerfile.dev ./client

script:
  - docker run docker.io/aliamyn/fibreact-test npm run test -- --coverage

after_success:
  - docker build -t aliamyn/multi-client ./client
  - docker build -t aliamyn/multi-nginx ./nginx
  - docker build -t aliamyn/multi-server ./server
  - docker build -t aliamyn/multi-worker ./worker
