sudo: required
services:
  - docker

before_install:
  - docker build -e CI=true -t aliamyn/fibreact-test -f ./client/Dockerfile.dev ./client

script:
  - docker run docker.io/aliamyn/fibreact-test npm run test -- --coverage

after_success:
  - docker build -t aliamyn/multi-client ./client
  - docker build -t aliamyn/multi-nginx ./nginx
  - docker build -t aliamyn/multi-server ./server
  - docker build -t aliamyn/multi-worker ./worker
   # login to docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  # take those images and push them to docker hun
  - docker push docker.io/aliamyn/multi-client
  - docker push docker.io/aliamyn/multi-nginx
  - docker push docker.io/aliamyn/multi-server
  - docker push docker.io/aliamyn/multi-worker
